### ISSUE TITLE
using array input cat command fails for empty arguments

### ISSUE THREAD

**Issue by thomasoberthanner** [jjwilly16/node-pdftk#1]
When using an array as input for cat command (no handles), these problems occur:
no argument given for catCommand
`pdftk.input([a, b]).cat()`
throws error (split method called on undefined)

empty string as catCommand
`pdftk.input([a, b]).cat('')`
only first file "a" used, all others ignored.

`pdftk.input([a, b]).cat(' ')`
only first file "a" used, all others ignored.

`pdftk.input([a, b]).cat([])` 
works as expected

**Comment by jjwilly16** [comment]
Sorry this took so long, I didn't receive my notification. 

Just committed the fix and published to npm as well. Reinstall and you should be good to go.

I see someone else already ran into this problem [here](https://github.com/gldmtr/node-pdftk/commit/f109c85efed0909d0ff8f45cce9fe2251aaab4f9) so I adopted his quick fix.
