### ISSUE TITLE
Insert Images

### ISSUE THREAD

**Issue by ahermundson** [jjwilly16/node-pdftk#14]
**Is your feature request related to a problem? Please describe.**
I was wondering if it would be possible to insert images.

**Describe the solution you'd like**
Pass a dataUri or ArrayBuffer on the data object and insert the image.

Thanks for all your work on this library. It works great!

**Comment by jjwilly16** [comment]
Sorry, this is out of scope for this project. This is just a wrapper around [PdfTk](https://www.pdflabs.com/tools/pdftk-server/). If someone showed me that this was possible to do with this tool, I'd be happy to look into it, but I'm pretty sure it's not.

There are ways to stamp an image onto a PDF, but it's a little more involved. You can create a transparent PDF with your image pre-placed on it then stamp it onto the source PDF - or create this stamp file dynamically with something like [pdfkit](https://github.com/devongovett/pdfkit). 

I'll create an example and post a link here - I'll keep this issue open for now.

**Comment by ahermundson** [comment]
No apologies necessary. Thanks for the information. I will look into pdfkit. Thanks.
