### ISSUE TITLE
Stamp Method does not call Then or Catch

### ISSUE THREAD

**Issue by cfernandomaciel** [jjwilly16/node-pdftk#15]
I have the following piece of code:
```

addWatermark: (input, output, cb) => {
        pdftk
            .input(input)
            .stamp('./pdftools/logo.pdf')
            .output(output)
            .then((buffer) => {
                logger.info('WATTERMARK-APPLYING-LOG: going to call watermarkCallback');
                cb("", "pdf has been branded", "");
            })
            .catch((err) => {
                logger.info("PDF-BRANDING - WATTERMARK-APPLYING-ERROR: " + err);
                cb(err, null, err);
            });

    }
```

It's a pretty straight forward piece of code, no magic, nothing really to it, just vanilla node-pdftk.
It executes the input method, then the stamp one, and the output. 
The problem is that it never reaches the Then, and Catch methods. It just falls outside the method.

I tried many different approaches, but I cannot seem to find the reason. 

Input, output, and cb params are loaded correctly, but yet, Then and Catch do not work.

I'm using node-pdfk v 1.3.0

edit: I've updated to node-pdftk v 1.3.1 (latest) and the bug continues.

**Comment by jjwilly16** [comment]
#18 should fix this. Closing the issue
