### ISSUE TITLE
Accept number inputs

### ISSUE THREAD

**Issue by ionizer** [jjwilly16/node-pdftk#24]
**Is your feature request related to a problem? Please describe.**
Currently, this `pdftk` library will throw an error upon inputting a JSON with number property (e.g. `{"some_field": 1}`).

**Describe the solution you'd like**
It would be good if the library will accept numbers, by converting it to string automatically. This should be achievable by using JS's `Number.prototype.toString()` or some other way.

**Describe alternatives you've considered**
At least, it should be documented clearly that `pdftk` doesn't take numbers

**Comment by jjwilly16** [comment]
Good catch! Look for version 2.0.3 in npm later today
