### ISSUE TITLE
Cannot set the checkbox when filling PDF.

### ISSUE THREAD

**Issue by maielo** [jjwilly16/node-pdftk#25]
**Describe the bug**
Cannot set the checkbox when filling PDF.

**To Reproduce**
I have dumbed the avalaible fields.
```sh
$ pdftk some_pdf.pdf dump_data_fields_utf8
---
FieldType: Button
FieldName: Zaškrtávací pole 01
FieldFlags: 0
FieldJustification: Left
FieldStateOption: Ano0
FieldStateOption: Ano1
FieldStateOption: Ano2
FieldStateOption: Ano3
FieldStateOption: Ano4
FieldStateOption: Ano5
FieldStateOption: Ano6
FieldStateOption: Off
```

trying to set it using :

```js
pdftk
            .input(originalPdfPath)
            .fillForm({
               'Zaškrtávací pole 01' : 'Ano0',
               'Textové pole3' : 'Test using UTF8 field name',
             })
            .output()
            .then(buffer => {

                return buffer;
            }).catch((e) => {
                console.error(e)
            })
```

- The textfield 'Textové pole3' gets filled (so i guess UTF8 is not a problem)
- the checkbox doesn't, even after renaming it to "field1" etc. 

**Expected behavior**
Fill the checkbox

**Desktop (please complete the following information):**
 - Windows 10

**Comment by jjwilly16** [comment]
Try setting the checkbox value to 'Yes'. [See an explanation here](https://stackoverflow.com/a/2420832/5432480).

**Comment by icodeforlove** [comment]
@jjwilly16 that actually worked

**Comment by blocks-master** [comment]
I tried setting the check box to "yes" and "Yes" but it's not working.
.fillForm({
"isSingle": "Yes"
})
