### ISSUE TITLE
pdftk error if permissions passed as concatenated string

### ISSUE THREAD

**Issue by Reddok** [jjwilly16/node-pdftk#26]
**Describe the bug**
When you set permissions in pdftk if number of permissions are more then one, pdftk return error about unexpected data in output section.
For example:
```console
Error: Unexpected data in output section:
      FillIn CopyContents
Exiting.
Errors encountered.  No output created.
Done.  Input errors, so no output created.
```

It occurs when permission array passed in spawn like concatenated string.

**To Reproduce**

```javascript
const pdftk = require('node-pdftk');

// Works
pdftk
    .input(['Turgor.pdf'])
    .allow(['FillIn'])
    .output('Turgor_secured.pdf')
    .then(() => {
        console.log('done 1 ');
    })
    .catch(err => {
        console.log(1, err);
    });

// Don't works
pdftk
    .input(['Turgor.pdf'])
    .allow(['FillIn', 'CopyContents'])
    .output('Turgor_secured.pdf')
    .then(() => {
        console.log('done 2');
    })
    .catch(err => {
        console.log(2, err);
    });
```

**Expected behavior**
Create a pdf file with proper permissios without error.

**Comment by jjwilly16** [comment]
Sorry for the delay. Hopefully I will get to this sometime this week

**Comment by jjwilly16** [comment]
Good catch. This was definitely a bug. I'll publish 2.1.1 to npm today with the fix.
