### ISSUE TITLE
MacOS note re: pdftk version

### ISSUE THREAD

**Issue by jelling** [jjwilly16/node-pdftk#3]
PDFTk unfortunately does not link to the most recent MacOS version from their home page. So if a user of your library uses MacOS >= 10.11, PDFTk won't work at all but they'll likely blame the wrapper. 

The correct PDFTk version is at https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/pdftk_server-2.02-mac_osx-10.11-setup.pkg

I emailed the author to update his page but this has been an open issue for a year: https://stackoverflow.com/questions/39750883/pdftk-hanging-on-macos-sierra

**Comment by jjwilly16** [comment]
Thanks for point that out! I added a note to the README.

**Comment by electrichead** [comment]
I think this issue shouldn't be closed - the README wasn't updated with the link. I wasted so much time because I got the link from the site but it just hung indefinitely.

OP's link needs to be in the README explicitly!

**Comment by mikermcneil** [comment]
For others finding this, as @jelling pointed out, the filename is the giveaway.  If the filename of your installer doesn't mention osx 10.11, then you probably have the old one.

**Comment by owlstack** [comment]
Please update the README!! I had the same issue and spend some time on debugging!

**Comment by TomGranot** [comment]
Sent Sid a message on Linkedin and over email. Let's see if it'll help..
