### ISSUE TITLE
if pdftk waring, this program will throw err

### ISSUE THREAD

**Issue by lanceInGz** [jjwilly16/node-pdftk#33]
i think this is a mistake in output method.  when pdftk throw a waring,  even if i set ignoreWarnings() , but not use,  this programe still throw err . and then ,i  found  this code have mistake.
```
 if (!(this._ignoreWarnings && data.toString().toLowerCase().includes('error'))) {
```
it should be
```
 if (!(this._ignoreWarnings && !data.toString().toLowerCase().includes('error'))) {
```
miss '!' before data.toString()

**Comment by jjwilly16** [comment]
Fixed in 2.1.2. Thanks!
