### ISSUE TITLE
Null values FDF bug fixes not deployed to npm in 2.1.2

### ISSUE THREAD

**Issue by productioncoder** [jjwilly16/node-pdftk#38]
**Describe the bug**
Hi @jjwilly16 

first of all thank you very much for this great package.
In version `2.1.2`, a bugfix was pushed that ignores `null` fields in the payload with 5c91fe8bde54f4f84f1ea59000dbeab74152b846

Unfortunately it seems as if this change was not published to `npm` in `2.1.2`
**To Reproduce**
1. Create a new dummy project in a temporary directory with
```
npm init -y
```
2. Install `node-pdftk` package
```
npm i node-pdftk
```
and verify in `package_lock.json` that the currently installed version is `2.1.2`

```
"node-pdftk": {
      "version": "2.1.2",
      "resolved": "https://registry.npmjs.org/node-pdftk/-/node-pdftk-2.1.2.tgz",
      "integrity": "sha512-xapuoppEweAHOLdolxinm3kmEGtQSrWxu5M3fnu+Y3ABpVGx+Xc4NpeGahTVRdFMGhufLyyoBNnUJPUwXVNU9A=="
    }
```
3. Navigate to `node_modules/node-pdftk/index.js` and search for the `generateFdfFromJSON` method (starts at line `188`).

Note that in line `204`, we have the following if statement
```
if (data.hasOwnProperty(prop)) {
```

However I think it should actually be
```
if (data.hasOwnProperty(prop) && data[prop] !== null && data[prop] !== undefined) {
```
because there is a commit as of Github version `2.1.2` which fixes the `FDF` `null` bug: 5c91fe8bde54f4f84f1ea59000dbeab74152b846

Because of this the FDF form filling still fails if any of the fields is null with the `2.1.2` version of this package installed via `npm`

**Expected behavior**
The bugfix that is already on master should also be pushed to `npm` so that FDF files can be generated even if fields are `null`.

The solution would be to push the latest changes to `npm`.

**Comment by jjwilly16** [comment]
Sorry for the delay. This fix is published to npm v2.1.3
