### ISSUE TITLE
Allow pdftk path to be configured so as to avoid global pdftk installation

### ISSUE THREAD

**Issue by nul** [jjwilly16/node-pdftk#4]
To have a self-contained application, the pdftk binary can be included as an asset of the application and used from there rather than having a global install of pdftk.

Can the include optionally pass param to specify the path (command) to the pdftk binary?

**Comment by jjwilly16** [comment]
This sounds reasonable. Unfortunately I won't have time to look into this until after the holidays. I'll update this next month sometime.

**Comment by jjwilly16** [comment]
I've created a [new branch](https://github.com/jjwilly16/node-pdftk/tree/issue4) with a pdftk binary that works in Windows. I don't have a lot of time to devote to this, but it's a start. Feel free to pull and play around with it.

If you (or anyone else) would like to contribute by adding Linux or Mac binaries, that would be awesome!

**Comment by jjwilly16** [comment]
#18 enables the option to specify a binary path. Closing this issue
