### ISSUE TITLE
Function generateFdfFromJSON throwing First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object Error

### ISSUE THREAD

**Issue by cfernandomaciel** [jjwilly16/node-pdftk#6]
I'm using the fillForm method, passing one JSON Object as designed. My node-pdftk version is 5.5.1, node -v: 8.9.3. 
It keeps throwing the following error, with the following stack, no matter how hard I try to stick to the pattern: 

`TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:202:9)
    at Function.generateFdfFromJSON (/src/node_modules/node-pdftk/index.js:181:28)
    at PdfTk.fillForm (/src/node_modules/node-pdftk/index.js:439:52)
    at Object.fillForm (/src/routes/pdf/pdf_worker.js:33:14)
    at Object.createContractJob (/src/routes/core/flag_step.js:301:24)
    at callback (/src/routes/listeners/robot_signals.js:21:14)
    at SubscriptionDefinition.invokeSubscriber (/src/node_modules/postal/lib/postal.js:172:19)
    at /src/node_modules/postal/lib/postal.js:529:21
    at /src/node_modules/postal/lib/postal.js:418:5
    at arrayEach (/src/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/src/node_modules/lodash/lodash.js:9359:14)
    at /src/node_modules/postal/lib/postal.js:538:7
    at /src/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/src/node_modules/lodash/lodash.js:3001:24)
    at /src/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/src/node_modules/lodash/lodash.js:9359:14)
`

As said, the FDF content is in proper json format, here it is:

`
{ 
    fdf: 
     { city: 'Zug',
       city_1: 'Zug',
       city_2: 'Zug',
       city_3: 'Zug',
       company_address: 'Gubelstrasse 12, 6300',
       company_address_1: 'Gubelstrasse 12, 6300',
       company_address_2: 'Gubelstrasse 12, 6300',
       company_address_3: 'Gubelstrasse 12, 6300',
       zip: '88584',
       zip_1: 'Gubelstrasse 12, 6300',
       zip_2: 'Gubelstrasse 12, 6300',
       zip_3: 'Gubelstrasse 12, 6300',
       date: 'Fri Jan 05 2018 07:47:39 GMT+0000 (UTC)',
       date_1: 'Fri Jan 05 2018 07:47:39 GMT+0000 (UTC)',
       date_2: 'Fri Jan 05 2018 07:47:39 GMT+0000 (UTC)',
       signature_date: 'Fri Jan 05 2018 07:47:39 GMT+0000 (UTC)',
       date_end: 'Thu Apr 05 2018 07:47:39 GMT+0000 (UTC)',
       hour_rate: '30 Euros',
       client_name: 'André',
       client_name_1: 'André',
       client_name_2: 'André',
       client_name_3: 'André',
       city_zipcode: '88485000' },
    contract_id: '5a4f889b81d40e457ef2dd38' } 
`

How can I fix that?

**Comment by jjwilly16** [comment]
It looks like you are passing an object with a nested object inside of it. That will not work. You are going to want to send a flat object. Just remove the 'fdf' key and bring it's contents up to the base level of the object.

I'll update the documentation to make sure this is more clear in the future. Thanks!

**Comment by cfernandomaciel** [comment]
Thanks @jjwilly16! That was exactly the case!
