### ISSUE TITLE
.cat() with Buffers

### ISSUE THREAD

**Issue by bschulz87** [jjwilly16/node-pdftk#7]
the .cat() method isn't working with buffers as input.

`" does not exist
    at Function.input (/node_modules/node-pdftk/index.js:88:68)
    at pdftk.input.stamp.output.then.catch.then.buffer (/index.js:108:6)
    at <anonymous>
`

when outputting the used buffers as files and then cat, it works as expected.

`
pdftk
    .input({
        A: fs.readFileSync('./page1.pdf'),
        B: './page2.pdf',
    })
    .cat('A B')
`

**Comment by jjwilly16** [comment]
Oops - it looks like I completely missed the functionality to handle buffers when using handles.

A fix for this is in. See #8 or re-install from npm (version 1.2.2). Thanks for bringing this to my attention!
