### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by mattvague** [jjwilly16/node-pdftk#9]
Hey there,

Library looks nice! I'd like to use it for a project, but I'm a little hesitant because I don't see any tests. Is this something you'd accept a PR for?

**Comment by jjwilly16** [comment]
Thanks! 

Absolutely. I've been meaning to write them but haven't found the time.

**Comment by jjwilly16** [comment]
Tests have been started - only around 50% coverage for now, but they're still in progress. Closing this issue
